/*!
 * \file op/parallel.cc
 * \brief Define Parallel for operator
 */

#include "parallel.h"
#include "support/check.h"
#include <tvm/ffi/extra/structural_equal.h>
#include <tvm/ir/cast.h>
#include <tvm/runtime/logging.h>

#include <algorithm>
#include <limits>
#include <map>
#include <string>
#include <tvm/tirx/analysis.h>
#include <tvm/tirx/op.h>
#include <tvm/tirx/stmt_functor.h>
#include <unordered_set>

#include "../layout/layout.h"
#include "../layout/utils.h"
#include "../transform/loop_partition.h"
#include "../transform/loop_vectorize.h"
#include "arith/int_operator.h"
#include "backend/common/target_utils.h"
#include "builtin.h"
#include "pto_index_analysis.h"
#include "reducer.h"
#include "span_utils.h"
#include "utils.h"

namespace tvm {
namespace tl {

using namespace tirx;
using namespace ffi;

namespace {

class IfBufferRemapLoopGenerator : public StmtExprMutator {
public:
  static For run(Stmt stmt, Map<Buffer, Buffer> buffer_remap,
                 Map<Buffer, Layout> layout_map) {
    IfBufferRemapLoopGenerator generator(buffer_remap, layout_map);
    return Downcast<For>(generator(std::move(stmt)));
  }

private:
  IfBufferRemapLoopGenerator(Map<Buffer, Buffer> buffer_remap,
                             Map<Buffer, Layout> layout_map)
      : buffer_remap_(buffer_remap), layout_map_(layout_map) {}

  PrimExpr VisitExpr_(const BufferLoadNode *op) final {
    auto load = Downcast<BufferLoad>(StmtExprMutator::VisitExpr_(op));

    if (buffer_remap_.count(load->buffer)) {
      auto new_indices = layout_map_[load->buffer]->Forward(load->indices);
      auto new_buffer = buffer_remap_[load->buffer];

      return BufferLoad(new_buffer, new_indices);
    }
    return load;
  }

  Stmt VisitStmt_(const BufferStoreNode *op) final {
    auto store = Downcast<BufferStore>(StmtExprMutator::VisitStmt_(op));
    if (buffer_remap_.count(store->buffer)) {
      auto new_indices = layout_map_[store->buffer]->Forward(store->indices);
      auto new_buffer = buffer_remap_[store->buffer];
      return BufferStore(new_buffer, store->value, new_indices);
    }
    return store;
  }

  Map<Buffer, Buffer> buffer_remap_;
  Map<Buffer, Layout> layout_map_;
};

// Choose a vector width for non-fragment SIMT loops while keeping the full
// thread extent active.  The loop partitioner covers work in chunks of
// `thread_extent * vector_size`; when the logical loop size is ragged, the
// excess points are guarded as padding.  Prefer the candidate that introduces
// the fewest padded points, and keep the wider vector width on ties.
int SelectMinPaddingVectorSize(int max_vector_size, PrimExpr loop_total_size,
                               PrimExpr thread_extent,
                               arith::Analyzer *analyzer) {
  ICHECK_GT(max_vector_size, 0);
  const int64_t *total = as_const_int(analyzer->Simplify(loop_total_size));
  const int64_t *threads = as_const_int(analyzer->Simplify(thread_extent));
  // This is a compile-time planning heuristic.  If the size is symbolic, keep
  // the vectorizer's original choice and rely on the existing runtime guard.
  if (total == nullptr || threads == nullptr || *threads <= 0) {
    return max_vector_size;
  }

  int best_vector_size = max_vector_size;
  int64_t best_padding = 0;
  bool has_best = false;
  PrimExpr total_i64 = cast(DataType::Int(64), loop_total_size);
  // Candidate vector widths are generated by halving the maximum legal width,
  // matching the rest of the vectorization planner's power-of-two choices.
  for (int candidate = max_vector_size; candidate >= 1; candidate /= 2) {
    PrimExpr partition_width =
        IntImm(DataType::Int(64), (*threads) * static_cast<int64_t>(candidate));
    // Use tirx::ceildiv instead of hand-rolled integer arithmetic so the same
    // simplification and constant-folding rules are used as TIR expressions.
    PrimExpr covered_expr = analyzer->Simplify(
        ceildiv(total_i64, partition_width) * partition_width);
    const int64_t *covered = as_const_int(covered_expr);
    if (covered == nullptr) {
      return max_vector_size;
    }
    int64_t padding = *covered - *total;
    if (!has_best || padding < best_padding ||
        (padding == best_padding && candidate > best_vector_size)) {
      has_best = true;
      best_padding = padding;
      best_vector_size = candidate;
    }
    if (candidate == 1) {
      break;
    }
  }
  return best_vector_size;
}

} // anonymous namespace

/**
 * @brief Handle a parallel For node during traversal, collecting loop metadata.
 *
 * Visits a parallel loop, asserts the loop is parallel, records a data-parallel
 * IterVar for the loop, and binds the loop variable range into the analyzer
 * scope. Continues traversal into the loop body.
 */
void ParallelLoopNestVisitor::VisitStmt_(const ForNode *op) {
  if (op->kind == ForKind::kParallel)
    p->loop_vars_.push_back(IterVar(Range(op->min, op->extent), op->loop_var,
                                    IterVarType::kDataPar));
  else
    p->inner_vars_.Set(op->loop_var,
                       IterVar(Range(op->min, op->extent), op->loop_var,
                               IterVarType::kOrdered));
  p->analyzer_.Bind(op->loop_var, Range::FromMinExtent(op->min, op->extent));
  StmtExprVisitor::VisitStmt_(op);
}

void ParallelLoopNestVisitor::VisitStmt_(const BufferStoreNode *op) {
  if (IsFragmentBuffer(op->buffer)) {
    p->RecordBufferAccess(op->buffer, op->indices, /*is_write=*/true);
  }
  StmtExprVisitor::VisitStmt_(op);
}

void ParallelLoopNestVisitor::VisitExpr_(const BufferLoadNode *op) {
  if (IsFragmentBuffer(op->buffer)) {
    p->RecordBufferAccess(op->buffer, op->indices, /*is_write=*/false);
  }
  StmtExprVisitor::VisitExpr_(op);
}

void ParallelLoopNestVisitor::VisitExpr_(const CallNode *op) {
  if (op->op.same_as(reducer_update())) {
    ReducerUpdateArgs update = ParseReducerUpdate(op);
    p->reducer_updates_.push_back(ParallelOpNode::ReducerUpdateRecord{
        update.reducer, update.indices, update.value});
  }
  // Recurse into the args: the contribution's fragment loads must still be
  // recorded (the reducer's own BufferLoad descriptor is scope-filtered out).
  StmtExprVisitor::VisitExpr_(op);
}

ParallelOpNode::ParallelOpNode(For root) : root_(root), V(this) {
  V.VisitStmt(root);
  // Cache any annotated layout/predicate on the outermost loop.
  using namespace attr;
  if (root_->annotations.count(kParallelLoopLayout)) {
    annotated_layout_unbound_ =
        Downcast<Fragment>(root_->annotations.Get(kParallelLoopLayout).value());
  }
  if (root_->annotations.count(kParallelLoopPredicate)) {
    annotated_predicate_ = Downcast<PrimExpr>(
        root_->annotations.Get(kParallelLoopPredicate).value());
  }
  if (auto padding_guard_anno =
          root_->annotations.Get(kParallelLoopRequiresPaddingGuard)) {
    if (auto padding_guard_bool = padding_guard_anno.value().try_cast<Bool>()) {
      annotated_requires_padding_guard_ = padding_guard_bool.value()->value;
    } else if (auto padding_guard_int =
                   padding_guard_anno.value().as<IntImmNode>()) {
      annotated_requires_padding_guard_ = padding_guard_int->value != 0;
    } else {
      LOG(WARNING) << "Loop annotation `" << kParallelLoopRequiresPaddingGuard
                   << "` expects Bool value (True/False), but got "
                   << padding_guard_anno.value().GetTypeKey()
                   << ". Ignore override.";
    }
  }
  // Collect cross-thread access info and buffer store info.
  PostOrderVisit(root_, [&](const ObjectRef &obj) {
    if (const auto *store = obj.as<BufferStoreNode>()) {
      auto buffer = store->buffer;
      if (IsSharedBuffer(buffer) || IsGlobalBuffer(buffer)) {
        has_cross_thread_access_ = true;
        store_shared_global_buffers_.emplace_back(buffer);
      } else if (IsFragmentBuffer(buffer)) {
        store_fragment_buffers_.emplace_back(buffer);
      }
    } else if (const auto *load = obj.as<BufferLoadNode>()) {
      if (IsSharedBuffer(load->buffer) || IsGlobalBuffer(load->buffer)) {
        has_cross_thread_access_ = true;
      }
    }
  });
}

TileOperator ParallelOpNode::Clone() const {
  auto op = make_object<ParallelOpNode>(*this);
  return ParallelOp(op);
}

void ParallelOpNode::ExpandBindValues(
    const Map<Var, PrimExpr> &bind_var_to_expr) {
  if (bind_var_to_expr.empty())
    return;

  // Helper function to recursively find BufferLoads through Bind values
  std::function<void(const PrimExpr &)> expand = [&](const PrimExpr &expr) {
    PostOrderVisit(expr, [&](const ObjectRef &node) {
      if (auto bl = node.as<BufferLoadNode>()) {
        if (IsFragmentBuffer(bl->buffer)) {
          RecordBufferAccess(bl->buffer, bl->indices, /*is_write=*/false);
        }
      } else if (auto var_node = node.as<VarNode>()) {
        auto var = GetRef<Var>(var_node);
        if (bind_var_to_expr.count(var)) {
          expand(bind_var_to_expr[var]);
        }
      }
    });
  };

  // Only expand Bind values that are used in root_
  // First, collect all vars used in root_
  std::unordered_set<const VarNode *> used_vars;
  PostOrderVisit(root_, [&](const ObjectRef &node) {
    if (auto var_node = node.as<VarNode>()) {
      used_vars.insert(var_node);
    }
  });

  // Only expand Bind values for vars that are actually used in root_
  for (const auto &[var, expr] : bind_var_to_expr) {
    if (used_vars.count(var.get())) {
      expand(expr);
    }
  }
}

void ParallelOpNode::RecordBufferAccess(const Buffer &buffer,
                                        const Array<PrimExpr> &indices,
                                        bool is_write) {
  auto it = indice_map_.find(buffer);
  if (it != indice_map_.end()) {
    ICHECK(StructuralEqual()(it->second.indices, indices))
        << buffer << ": " << indices << " and " << it->second.indices
        << SpanHintSuffix(buffer->span);
  } else {
    BufferAccessInfo info;
    info.indices = indices;
    it = indice_map_.emplace(buffer, std::move(info)).first;
    access_order_.push_back(buffer);
  }
  if (is_write) {
    it->second.is_write = true;
  } else {
    it->second.is_read = true;
  }
}

const ParallelOpNode::BufferAccessInfo &
ParallelOpNode::GetAccessInfo(const Buffer &buffer) const {
  auto it = indice_map_.find(buffer);
  ICHECK(it != indice_map_.end())
      << "Missing access info for buffer " << buffer;
  return it->second;
}

bool ParallelOpNode::IsBufferCompletelyReplicated(
    const Buffer &buffer, const LayoutMap &layout_map) const {
  if (!IsFragmentBuffer(buffer))
    return false;
  auto frag = layout_map[buffer].as<Fragment>().value();
  // buffer indices should be IntImm
  for (const auto &index : GetAccessInfo(buffer).indices) {
    if (!index.as<IntImmNode>()) {
      return false;
    } else if (index.as<IntImmNode>()->value != 0) {
      LOG(FATAL) << "buffer " << buffer << " is not completed replicated";
    }
  }
  return frag->IsCompletedReplicated();
}

Stmt ParallelOpNode::Lower(const LowerArgs &lower_args,
                           arith::Analyzer *analyzer) const {
  return root_;
}

// (annotations parsed in ctor; adoption happens in InferLayout)

bool ParallelOpNode::IsCommonAccessIndice(const Buffer &buffer) const {
  auto common_indice = loop_vars_.Map([](const auto &iv) { return iv->var; });
  return StructuralEqual()(GetAccessInfo(buffer).indices, common_indice);
}

/*! \brief Infer the layout for parallel operations based on different inference
 * levels
 *
 * The inference level controls how aggressively we try to infer and optimize
 * layouts:
 * - kStrict (2): Most conservative level. Only allows explicitly defined
 * layouts. Returns empty layout map if loop_layout_ is not already defined.
 *                Used when exact layout control is required.
 *
 * - kCommon (1): Intermediate level between strict and free.
 *                Allows common layout patterns while maintaining some
 * constraints.
 *
 * - kFree (0):   Most permissive level. Allows maximum optimization freedom.
 *                Will attempt layout inference even without source buffers.
 *                Can generate new layouts based on vectorization and thread
 * bounds. Used when maximum performance optimization is desired.
 */
LayoutMap ParallelOpNode::InferLayout(const LayoutInferArgs &layout_args,
                                      InferLevel level) const {
  if (loop_layout_inferred_) {
    // Fragments this loop touches can receive their layouts only after the
    // loop itself was solved (the engine re-enqueues the loop when such a
    // late layout lands; a reserved reducer destination always arrives
    // late). The frozen loop layout must then be re-checked against the
    // current fragment layouts: a mismatch means this attempt paired a
    // solved loop with fragments it cannot address, and the thrown
    // LayoutConflictException lets free mode discard the attempt. Strict and
    // common levels have no discard channel, so they keep the early-out.
    if (level == InferLevel::kFree && loop_layout_.defined()) {
      ValidateCandidateAgainstFragments(loop_layout_, layout_args,
                                        /*throw_on_error=*/true,
                                        /*check_forward_index=*/false);
    }
    return {};
  }
  loop_layout_requires_padding_guard_ = false;

  // Expand Bind values to find fragment buffer accesses
  if (!layout_args.bind_var_to_expr.empty()) {
    const_cast<ParallelOpNode *>(this)->ExpandBindValues(
        layout_args.bind_var_to_expr);
  }

  // PTO SIMD path: parallel loops inside a PTO SIMD_VF block distribute
  // over [0, L) logical lanes. Build the lane fragment directly
  // (vectorize_size = 1, no SIMT vector-width selection) and skip the
  // fragment-buffer inference machinery — the first version only supports
  // shared/global buffers with continuous access, checked later by
  // VerifyParallelToPTO.
  if (layout_args.in_pto_simd_vf) {
    return InferPtoSimdLayout(layout_args);
  }

  if (level == InferLevel::kStrict) {
    LayoutMap results;
    // Deduce buffers that should be complicated replicated.
    // For example:
    // for i in T.Parallel(m):
    //   fragment[0] = x[i]
    // then fragment[0] must be replicated on all threads.
    for (const auto &buffer : access_order_) {
      const auto &access = GetAccessInfo(buffer);
      if (layout_args.layout_map.count(buffer)) {
        continue;
      }
      if (!IsFragmentBuffer(buffer))
        continue;

      // Check if all indices are zero
      bool all_indices_zero = true;
      for (const auto &index : access.indices) {
        if (const auto *imm = index.as<IntImmNode>()) {
          if (imm->value != 0) {
            all_indices_zero = false;
            LOG(FATAL)
                << "Fragment buffer access with non-zero index [" << imm->value
                << "] is not supported. "
                << "Only fragment[0] access is allowed within T.Parallel loop."
                << SpanHintSuffix(buffer->span);
          }
        } else {
          // Non-constant index, not all zero
          all_indices_zero = false;
        }
      }

      // Only set layout if all indices are zero
      if (all_indices_zero) {
        Array<IterVar> forward_vars;
        for (const auto &s : buffer->shape) {
          forward_vars.push_back(
              IterVar(Range(0, s), Var(), IterVarType::kDataPar));
        }
        Var rep;
        auto rep_iter = IterVar({0, layout_args.thread_bounds->extent}, rep,
                                IterVarType::kDataPar);

        // Use default fragment indexing (single output dim) to
        // stay consistent with other ops (e.g., ReduceOp), and
        // bind the thread range for comparability.
        const PrimExpr &forward_thread = rep;
        auto frag = Fragment(forward_vars, /*forward_index=*/{}, forward_thread,
                             rep_iter)
                        ->BindThreadRange(layout_args.thread_bounds);
        results.Set(buffer, frag);
      }
    }
    return results;
  }

  // Collect fragment buffers with const index and all fragment_buffers
  std::vector<Buffer> const_index_fragment_buffer, fragment_buffers;
  for (const auto &buffer : access_order_) {
    const auto &access = GetAccessInfo(buffer);
    if (!IsFragmentBuffer(buffer))
      continue;
    fragment_buffers.push_back(buffer);

    bool is_const_index = true;
    for (const auto &index : access.indices) {
      if (!index.as<IntImmNode>()) {
        is_const_index = false;
        break;
      }
    }
    if (is_const_index) {
      const_index_fragment_buffer.push_back(buffer);
    }
  }

  // Determine if common layout propagation should be applied.
  // If there are fragment buffers with non-constant indices, we need to
  // propagate the common layout pattern to ensure consistency across all
  // fragments. Example cases:
  //   - Need propagation: frag_a[0] = T.min(frag_a[0], frag_b[i])
  //     (const index frag_a interacts with non-const index frag_b)
  //   - No propagation needed: shared_a[i] = frag_a[0]
  //     (const index frag_a with non-fragment buffer)

  bool allow_layout_propgate =
      const_index_fragment_buffer.empty() ||
      (fragment_buffers.size() > const_index_fragment_buffer.size());

  // Step 1: try to infer loop's partition from a source fragment
  Buffer source_buffer, read_source_buffer;
  bool source_buffer_is_write = false;

  for (const auto &buffer : access_order_) {
    const auto &access = GetAccessInfo(buffer);
    if (layout_args.layout_map.count(buffer)) {
      // Validation side effect only (fatals on constant non-zero fragment
      // indices); the replication status itself does not steer source
      // selection — replicated reads are down-ranked by the ReplicateExtent
      // check below and by ChooseBestCandidate's heuristics.
      (void)IsBufferCompletelyReplicated(buffer, layout_args.layout_map);

      if (access.is_write) {
        source_buffer = buffer;
        source_buffer_is_write = true;
      } else {
        // Keep the buffer with largest number of indices
        // (which means the inference based on that buffer is more accurate)
        // as read_source_buffer to get more accurate layout
        // if the buffer is completed replicated, we don't need to infer the
        // layout from this buffer.
        if ((!read_source_buffer.defined() ||
             access.indices.size() >
                 GetAccessInfo(read_source_buffer).indices.size())) {
          read_source_buffer = buffer;
        }
        // If the buffer is not replicated and shape is equal to the
        // source_buffer, use it as source_buffer because the layout inference
        // is more accurate
        auto frag = layout_args.layout_map[buffer].as<Fragment>();
        if (frag.has_value() && is_one(frag.value()->ReplicateExtent()) &&
            !source_buffer.defined()) {
          source_buffer = buffer;
          source_buffer_is_write = false;
        }
      }
    }
  }
  // moved to ComputeLoopLayoutFromBuffer

  // A strict (user-annotated) reducer partial pins this nest's placement:
  // derive the loop layout from it ahead of any source-buffer heuristic.
  // Free mode only — a candidate that conflicts with already-solved
  // fragments throws in Step 2, and the attempt search may find an ordering
  // (this nest first, fragments completed from it) that satisfies the
  // annotation.
  Fragment pinned_reducer_candidate;
  if (!loop_layout_.defined() && level == InferLevel::kFree &&
      !reducer_updates_.empty()) {
    pinned_reducer_candidate = ComputeReducerPinnedCandidate(layout_args);
  }

  // Try to infer loop layout from buffers in order of preference only if we
  // don't already have a layout (e.g., from annotations):
  // 1. Annotated loop layout
  // 2. Loop layout pinned by an annotated reducer partial
  // 3. Non-replicated write buffer (most reliable)
  // 4. Non-replicated read buffer
  // 5. Fully replicated write buffer (backup, may cause issues)
  // 6. Free inference mode (no source buffer)
  if (!loop_layout_.defined() && annotated_layout_unbound_.defined()) {
    loop_layout_ = annotated_layout_unbound_.value()->BindThreadRange(
        layout_args.thread_bounds);
    loop_layout_requires_padding_guard_ = annotated_requires_padding_guard_;
    if (annotated_predicate_.defined()) {
      predicate_ = annotated_predicate_.value();
    }
  } else if (!loop_layout_.defined() && pinned_reducer_candidate.defined()) {
    loop_layout_ = pinned_reducer_candidate;
  } else if (!loop_layout_.defined() && source_buffer.defined() &&
             (allow_layout_propgate || source_buffer_is_write)) {
    loop_layout_ = ComputeLoopLayoutFromBuffer(source_buffer, layout_args);
  } else if (!loop_layout_.defined() && level == InferLevel::kFree) {
    // For free layout inference
    // In free inference, try two mechanisms and prefer the one that
    // minimizes replication while remaining compatible:
    // 1) compute_loop_layout_from_buffer (always correct but may
    // over-replicate) 2) PlanLoopPartition (often smaller replication)
    Fragment candidate_from_buffer;
    Fragment candidate_from_plan;
    bool selected_plan_candidate = false;

    if (read_source_buffer.defined() && allow_layout_propgate) {
      candidate_from_buffer =
          ComputeLoopLayoutFromBuffer(read_source_buffer, layout_args);
    }
    candidate_from_plan = ComputePlanCandidate(layout_args);

    // Choose the best candidate:
    if (candidate_from_buffer.defined() && candidate_from_plan.defined()) {
      loop_layout_ = ChooseBestCandidate(candidate_from_buffer,
                                         candidate_from_plan, layout_args);
      selected_plan_candidate = loop_layout_.same_as(candidate_from_plan);
    } else if (candidate_from_plan.defined()) {
      loop_layout_ = candidate_from_plan;
      selected_plan_candidate = true;
      DLOG(INFO) << "[FreeInfer] only PlanLoopPartition available, choose it.";
    } else if (candidate_from_buffer.defined()) {
      loop_layout_ = candidate_from_buffer;
      DLOG(INFO)
          << "[FreeInfer] only compute_from_buffer available, choose it.";
    }
    loop_layout_requires_padding_guard_ =
        selected_plan_candidate && indice_map_.empty();
  } else if (!loop_layout_.defined()) {
    // In non-free mode without a source buffer, if we don't have any layout
    // yet (e.g., no annotation), we have nothing to infer here.
    return {};
  }

  // Non-fragment SIMT loops may deliberately over-cover a ragged iteration
  // space; PartitionLoop emits guards for the padded points. Fragment/reducer
  // loops stay strict because padding would change per-thread ownership.
  auto injective_res =
      loop_layout_->DetectInjective(loop_layout_requires_padding_guard_);
  if (!injective_res->errors.empty()) {
    std::ostringstream oss;
    oss << "Loop layout is not injective: " << loop_layout_->DebugOutput()
        << '\n'
        << "  errors: " << injective_res->errors << '\n'
        << "  loop AST: " << root_;
    throw LoopLayoutInjectiveException(oss.str());
  }

  PrimExpr loop_thread_extent = loop_layout_->ThreadExtent();

  auto block_size = layout_args.thread_bounds->extent;
  if (loop_layout_.defined()) {
    if (loop_layout_->ThreadRange().defined()) {
      auto thread_range = loop_layout_->ThreadRange();
      block_size = thread_range->extent;
      AddPredicate(GE(InputPlaceholder(0), thread_range->min));
      AddPredicate(
          LT(InputPlaceholder(0), thread_range->min + thread_range->extent));
    }
  }

  if (!analyzer_.CanProveEqual(loop_thread_extent, block_size)) {
    AddPredicate(LT(InputPlaceholder(0),
                    loop_thread_extent + layout_args.thread_bounds->min));
  }

  // Step 2: Check that the loop's partition can correctly align with all source
  // fragment, and infer layout only when it's not yet layout-ed.
  ValidateCandidateAgainstFragments(
      loop_layout_, layout_args, /*throw_on_error=*/true,
      /*check_forward_index=*/false, source_buffer);

  // Step 3: Build replication guards
  BuildReplicationGuardsIfNeeded(
      layout_args, store_shared_global_buffers_, store_fragment_buffers_,
      has_cross_thread_access_, const_index_fragment_buffer);

  // Step 4: Collect buffer fragments
  LayoutMap results;
  for (const auto &buffer : access_order_) {
    if (!layout_args.layout_map.count(buffer)) {
      auto dst_layout = CompleteBufferFragment(buffer)->BindThreadRange(
          layout_args.thread_bounds);
      results.Set(buffer, dst_layout);
    }
  }

  // Step 5: propose the partial layout of every reducer this nest updates.
  // Deliberately proposed even when the reducer is already mapped: the
  // engine's widen-on-conflict commit rule arbitrates between update sites
  // whose induced layouts disagree.
  for (const auto &update : reducer_updates_) {
    results.Set(update.buffer, ProposeReducerPartial(update, layout_args));
  }

  loop_layout_inferred_ = true;
  return results;
}

PartialFragment ParallelOpNode::ProposeReducerPartial(
    const ReducerUpdateRecord &update,
    const LayoutInferArgs &layout_args) const {
  const Range &thread_bounds = layout_args.thread_bounds;
  auto wide = [&]() {
    return PartialFragment::FullyReplicated(
        update.buffer->shape, thread_bounds->extent, thread_bounds);
  };
  PartialFragment proposal;
  std::string narrow_reject;
  const int64_t *extent_ptr = as_const_int(thread_bounds->extent);
  const int64_t *min_ptr = as_const_int(thread_bounds->min);
  if (extent_ptr == nullptr || min_ptr == nullptr) {
    narrow_reject = "non-constant thread bounds";
    proposal = wide();
  } else if (tvm::transform::PassContext::Current()
                 ->GetConfig<Bool>(kReducerForceBaseline, Bool(false))
                 .value()) {
    // tl.reducer_force_baseline pins the whole epoch to the wide plan; the
    // decision now lives in the solved partial layout, so the pin applies at
    // the proposal, and the materializer just reads it back.
    narrow_reject = "forced baseline (tl.reducer_force_baseline)";
    proposal = wide();
  } else {
    ReducerUpdateSiteHint hint;
    hint.loop_layout = loop_layout_;
    hint.loop_vars = loop_vars_.Map([](const IterVar &iv) { return iv->var; });
    hint.indices = update.indices;
    hint.value = update.value;
    ReducerSiteAnalysis analysis = AnalyzeReducerUpdateSite(
        hint, update.buffer->shape, *extent_ptr, *min_ptr, &analyzer_);
    if (analysis.narrow_eligible) {
      proposal = PartialFragment::FromInduced(
          analysis.induced, IntImm(DataType::Int(32), analysis.combine_size));
    } else {
      narrow_reject = analysis.reason;
      proposal = wide();
    }
  }
  // A strict partial (user annotation) is authoritative. Failing here, at
  // the site, carries the narrow-rejection reason — far more actionable
  // than the commit point's bare layout mismatch.
  if (layout_args.strict_layout_map.count(update.buffer)) {
    const auto *pinned =
        layout_args.strict_layout_map[update.buffer].as<PartialFragmentNode>();
    if (pinned != nullptr && !proposal->IsEqual(pinned)) {
      std::ostringstream oss;
      oss << "Layout infer conflict for reducer `" << update.buffer->name
          << "`: this update site cannot realize the annotated "
          << "PartialFragment.\n  annotated: " << pinned->DebugOutput()
          << "\n  site's verdict: " << proposal->DebugOutput();
      if (!narrow_reject.empty()) {
        oss << "\n  narrow plan rejected because: " << narrow_reject;
      }
      oss << "\nAdjust the T.annotate_layout PartialFragment or the update "
          << "loop structure so they agree.";
      throw LayoutConflictException(oss.str());
    }
  }
  return proposal;
}

Fragment ParallelOpNode::ComputeReducerPinnedCandidate(
    const LayoutInferArgs &layout_args) const {
  for (const auto &update : reducer_updates_) {
    if (!layout_args.strict_layout_map.count(update.buffer)) {
      continue;
    }
    auto pinned =
        layout_args.strict_layout_map[update.buffer].as<PartialFragmentNode>();
    if (pinned == nullptr) {
      continue;
    }
    // Map each reducer dim to the loop var driving it (const-zero on unit
    // dims), and mark the surviving loop dims; the rest are reduction dims.
    std::vector<bool> is_output_dim(loop_vars_.size(), false);
    Array<PrimExpr> acc_args;
    bool mappable = true;
    for (const PrimExpr &index : update.indices) {
      if (const auto *var = index.as<VarNode>()) {
        int pos = -1;
        for (size_t i = 0; i < loop_vars_.size(); ++i) {
          if (loop_vars_[i]->var.get() == var) {
            pos = static_cast<int>(i);
            break;
          }
        }
        if (pos < 0 || is_output_dim[pos]) {
          mappable = false;
          break;
        }
        is_output_dim[pos] = true;
        acc_args.push_back(loop_vars_[pos]->var);
      } else if (is_zero(index)) {
        acc_args.push_back(make_zero(DataType::Int(32)));
      } else {
        mappable = false;
        break;
      }
    }
    if (!mappable || acc_args.size() != pinned->InputShape().size()) {
      continue;
    }
    // Flatten the reduction space and split it into the partial's combine
    // lanes in contiguous chunks (chunk-contiguous k per lane keeps the
    // per-thread reduction slice vectorizable).
    DataType dtype =
        loop_vars_.empty() ? DataType::Int(32) : loop_vars_[0]->var.dtype();
    PrimExpr flat = make_zero(dtype);
    int64_t flat_extent = 1;
    for (size_t i = 0; i < loop_vars_.size(); ++i) {
      if (is_output_dim[i]) {
        continue;
      }
      const int64_t *ext = as_const_int(loop_vars_[i]->dom->extent);
      if (ext == nullptr) {
        mappable = false;
        break;
      }
      flat = flat * loop_vars_[i]->dom->extent + loop_vars_[i]->var;
      flat_extent *= *ext;
    }
    const int64_t *lanes_ptr = as_const_int(pinned->CombineSize());
    const int64_t *rep_ptr = as_const_int(pinned->ReplicateExtent());
    if (!mappable || lanes_ptr == nullptr || rep_ptr == nullptr) {
      continue;
    }
    int64_t lanes = *lanes_ptr;
    int64_t copies = *rep_ptr / lanes; // ctor guarantees divisibility
    PrimExpr lane_expr;
    if (lanes <= 1) {
      lane_expr = make_zero(dtype);
    } else if (flat_extent % lanes != 0) {
      // Cannot split evenly; the annotation conflict (if any) is reported
      // by ProposeReducerPartial once the loop layout is solved elsewhere.
      continue;
    } else {
      lane_expr = FloorDiv(flat, make_const(dtype, flat_extent / lanes));
    }
    // Copy groups (annotated combine < replicate) come from the loop's own
    // replication: give the candidate a replicate var on the high side of
    // the pinned partial's `_rep = lane + combine * copy` coordinate, so
    // the projection at the update site reproduces the annotation.
    IterVar loop_rep; // stays null when the partial has no copy groups
    PrimExpr rep_expr = lane_expr;
    if (copies > 1) {
      loop_rep = IterVar(Range(make_zero(dtype), make_const(dtype, copies)),
                         Var("rep", dtype), IterVarType::kDataPar);
      rep_expr = lane_expr + make_const(dtype, lanes) * loop_rep->var;
    }
    PrimExpr loop_var_to_thread =
        analyzer_.Simplify(pinned->ForwardThread(acc_args, rep_expr));
    try {
      return Fragment(loop_vars_, {}, loop_var_to_thread, loop_rep)
          ->BindThreadRange(layout_args.thread_bounds);
    } catch (const Error &) {
      continue;
    }
  }
  return Fragment();
}

Optional<PrimExpr> ParallelOpNode::GetPredicate(PrimExpr thread_index) const {
  if (predicate_.defined()) {
    return Substitute(predicate_.value(),
                      {{InputPlaceholder(0), thread_index}});
  } else {
    return std::nullopt;
  }
}

Fragment ParallelOpNode::CompleteBufferFragment(const Buffer &buffer) const {
  ICHECK(loop_layout_.defined());
  if (IsCommonAccessIndice(buffer)) {
    return loop_layout_;
  }
  // Prefer a simple path: if original 2D indices form a bijective map, invert
  // them directly and avoid introducing a synthetic replicate dimension.
  {
    auto res2d =
        arith::DetectIterMap(GetAccessInfo(buffer).indices, ToVMap(loop_vars_),
                             1, arith::IterMapLevel::Bijective,
                             const_cast<arith::Analyzer *>(&analyzer_));
    if (res2d->errors.empty()) {
      Layout ind_inv2d =
          Layout(loop_vars_, GetAccessInfo(buffer).indices)->Inverse();
      PrimExpr indice_rep_extent = 1;
      PrimExpr loop_rep_extent = loop_layout_->ReplicateExtent();
      PrimExpr dest_buffer_rep_extent = indice_rep_extent * loop_rep_extent;
      Array<PrimExpr> fwd2;
      for (size_t i = 0; i < buffer->shape.size(); i++) {
        fwd2.push_back(InputPlaceholder(i));
      }
      PrimExpr thd_b2 =
          loop_layout_->ForwardThread(ind_inv2d->Forward(fwd2), std::nullopt);
      return Fragment(buffer->shape, {}, thd_b2, dest_buffer_rep_extent,
                      std::nullopt)
          ->CondenseReplicateVar();
    }
  }
  // Otherwise, infer an extra flattened iterator that captures truly-unused
  // pieces of the loop space (if any), then try inversion with it.
  PrimExpr rep_b = MakeFlattenedExpression(DivideUnusedIterators(
      GetAccessInfo(buffer).indices, loop_vars_, &analyzer_));
  auto bijective_indice = GetAccessInfo(buffer).indices;
  bijective_indice.push_back(rep_b);
  Layout ind_inv = Layout(loop_vars_, bijective_indice)->Inverse();

  PrimExpr indice_rep_extent =
      ind_inv->InputShape().back(); // this is the size of rep_b
  PrimExpr loop_rep_extent = loop_layout_->ReplicateExtent();
  PrimExpr dest_buffer_rep_extent = indice_rep_extent * loop_rep_extent;
  Array<PrimExpr> fwd;
  for (size_t i = 0; i < buffer->shape.size(); i++) {
    fwd.push_back(InputPlaceholder(i));
  }
  fwd.push_back(FloorMod(ReplicationPlaceholder(), indice_rep_extent));
  PrimExpr thd_b = loop_layout_->ForwardThread(
      ind_inv->Forward(fwd),
      FloorDiv(ReplicationPlaceholder(), indice_rep_extent));
  Fragment completed =
      Fragment(buffer->shape, {}, thd_b, dest_buffer_rep_extent, std::nullopt)
          ->CondenseReplicateVar();
  // Broadcast reads touched many times per thread produce an
  // occurrence-indexed replication whose (logical, replica) -> physical map
  // wraps around the thread extent and stops being injective; every
  // consumer that partitions by such a fragment throws.
  //
  // Example (issue #1729): a (2,) fragment read as `src[i]` inside a
  // coalesced `T.Parallel(2, 2560)` over 256 threads. The unused iterator
  // j becomes the replicate axis (2560 occurrences per element, condensed
  // to 640), yielding
  //   Fragment((2,) -> (2,), replicate: 640,
  //            thread: (_i * 640 + _rep) % 256, index: (_i,))
  // 2 x 640 (logical, replica) points cannot fit 256 x 2 physical cells:
  // replicas 0 / 256 / 512 of element 0 all land on (thread 0, slot 0).
  //
  // The thread OWNERSHIP the map describes is still sound -- the wrap
  // covering the whole thread extent means every thread reads the element
  // -- so for a buffer this loop only READS, fall back to the injective
  // canonical form of exactly that ownership:
  //   Fragment((2,) -> (2,), replicate: 256, thread: _rep, index: (_i,))
  // i.e. full replication. (For written buffers replication changes
  // execution multiplicity, so those keep the exact form and fail loudly
  // downstream.)
  if (!GetAccessInfo(buffer).is_write &&
      !completed->DetectInjective()->errors.empty()) {
    PrimExpr thread_extent = loop_layout_->ThreadExtent();
    const int64_t *extent_ptr = as_const_int(thread_extent);
    if (extent_ptr != nullptr) {
      Fragment replicated = Fragment::FullyReplicated(
          buffer->shape, static_cast<int>(*extent_ptr));
      if (loop_layout_->ThreadRange().defined()) {
        replicated = replicated->BindThreadRange(loop_layout_->ThreadRange());
      }
      return replicated;
    }
  }
  return completed;
}

TVM_FFI_STATIC_INIT_BLOCK() { ParallelOpNode::RegisterReflection(); }

bool ParallelOpNode::ValidateCandidateAgainstFragments(
    const Fragment &candidate, const LayoutInferArgs &layout_args,
    bool throw_on_error, bool check_forward_index,
    const Buffer &source_buffer) const {
  auto vars =
      loop_vars_.Map([](const IterVar &iv) { return PrimExpr(iv->var); });
  for (const auto &buffer : access_order_) {
    const auto &access = GetAccessInfo(buffer);
    if (!layout_args.layout_map.count(buffer))
      continue;
    auto fragment = layout_args.layout_map[buffer].as<Fragment>().value();
    std::ostringstream oss;
    bool success = true;
    if (access.is_read &&
        !ProveFragmentContains(candidate, fragment, vars, access.indices,
                               analyzer_, check_forward_index)) {
      if (throw_on_error) {
        oss << "Layout infer conflict between " << buffer << " and "
            << source_buffer << " in T.Parallel loop:" << '\n'
            << "    loop " << candidate->DebugOutput() << '\n'
            << "    fragment " << fragment->DebugOutput() << '\n';
      }
      success = false;
    }
    // Fragment writes need exact owner-thread compatibility. Coverage alone
    // allows extra loop threads to write local slots that belong to different
    // logical fragment elements under the buffer layout.
    if (access.is_write &&
        (!ProveFragmentContains(fragment, candidate, access.indices, vars,
                                analyzer_, check_forward_index) ||
         !ProveFragmentContains(candidate, fragment, vars, access.indices,
                                analyzer_, check_forward_index))) {
      if (throw_on_error) {
        oss << "Layout infer conflict between " << buffer << " and "
            << source_buffer << " in T.Parallel loop:" << '\n'
            << "    loop " << candidate->DebugOutput() << '\n'
            << "    fragment " << fragment->DebugOutput() << '\n';
      }
      success = false;
    }
    if (!success) {
      if (throw_on_error) {
        throw LayoutConflictException(oss.str());
      }
      return false;
    }
  }
  return true;
}

Fragment ParallelOpNode::ComputeLoopLayoutFromBuffer(
    const Buffer &buffer, const LayoutInferArgs &layout_args) const {
  Fragment src_layout = layout_args.layout_map[buffer].as<Fragment>().value();
  DLOG(INFO) << "[compute_loop_layout_from_buffer] infer from buffer `"
             << buffer << "` of layout " << src_layout->DebugOutput() << '\n';

  Fragment result;

  if (IsCommonAccessIndice(buffer)) {
    result = src_layout;
  } else {
    Var rep("_rep");
    auto rep_iter =
        IterVar({0, src_layout->ReplicateExtent()}, rep, IterVarType::kDataPar);
    PrimExpr loop_var_to_thread =
        src_layout->ForwardThread(GetAccessInfo(buffer).indices, rep);
    loop_var_to_thread = analyzer_.Simplify(loop_var_to_thread);
    PostOrderVisit(loop_var_to_thread, [&](const ObjectRef &objref) {
      if (auto opt_var = objref.as<Var>();
          opt_var && inner_vars_.count(*opt_var)) {
        std::ostringstream oss;
        oss << "Cannot lower access to thread-distributed fragment `"
            << buffer->name
            << "`: its elements are spread across CUDA threads, so the "
               "non-parallel loop variable `"
            << *opt_var
            << "` cannot be used to address them safely (thread map: "
            << loop_var_to_thread
            << "). Use T.reduce_sum for reductions, T.Parallel for elementwise "
               "access, or stage through shared memory to change the layout.";
        throw LayoutConflictException(oss.str());
      }
    });

    try {
      result = Fragment(loop_vars_, {}, loop_var_to_thread, rep_iter)
                   ->BindThreadRange(layout_args.thread_bounds);
    } catch (const Error &err) {
      std::ostringstream msg;
      msg << "Layout inference for buffer `" << buffer->name
          << "` failed inside `T.parallel` loop.";

      msg << "\nUnderlying TVM error: " << err.what();
      msg << "\nProblematic loop AST:\n " << root_;
      msg << "\nHint: ensure the loop extent divides the thread binding or "
             "adjust the fragment mapping.";
      LOG(FATAL) << msg.str() << SpanHintSuffix(buffer->span);
    }
  }
  DLOG(INFO) << "[compute_loop_layout_from_buffer] ... and get "
             << result->DebugOutput() << '\n';
  // Lei: This is a tradeoff, disable it for now.
  // // Try DeReplicate first to reduce replication if possible.
  // Fragment dereplicated_layout = candidate_from_buffer->DeReplicate();
  // if (ValidateCandidateAgainstFragments(
  //         dereplicated_layout, T, /*throw_on_error=*/false,
  //         /*check_forward_index=*/false,
  //         /*source_buffer=*/read_source_buffer)) {
  //   candidate_from_buffer = dereplicated_layout;
  // }
  return result;
}

// Pick the vectorized dimension of a two-layer
// Parallel nest from the buffer accesses. Both dimensions are tried as
// layout candidates under the same lane/chunk proof rules the consumers
// (Verify/Vectorize) use; a candidate is valid when its extent divides
// L and every access is continuous (or, for loads, lane-uniform) under
// it. The inner dimension wins when both are valid; no valid candidate
// is a layout error naming the failing access.
namespace {

class PtoAccessCollector : public tirx::StmtExprVisitor {
public:
  struct Access {
    Buffer buffer;
    Array<PrimExpr> indices;
    bool is_write;
    /*! The definition environment at this access's program point
     * (binds in scope, mirrors the consumers' lexical rules). */
    Map<Var, PrimExpr> bind_env;
  };
  std::vector<Access> accesses;

  void VisitStmt_(const BufferStoreNode *op) final {
    accesses.push_back({op->buffer, op->indices, /*is_write=*/true, bind_env_});
    tirx::StmtExprVisitor::VisitStmt_(op);
  }
  void VisitExpr_(const BufferLoadNode *op) final {
    accesses.push_back(
        {op->buffer, op->indices, /*is_write=*/false, bind_env_});
    tirx::StmtExprVisitor::VisitExpr_(op);
  }
  void VisitStmt_(const BindNode *op) final {
    // Flat sequence semantics (same as the consumers): the value is
    // visited *before* the var is registered, so a self reference is not
    // in scope; every bind — including load-valued ones — is registered
    // so ResolveIndexAliases can apply its loaded-value identity rule
    // along alias chains.
    tirx::StmtExprVisitor::VisitStmt_(op);
    bind_env_.Set(op->var, op->value);
  }
  void VisitStmt_(const AttrStmtNode *op) final {
    // Nested statement scope (mirror of the consumers' rule):
    // binds defined inside an AttrStmt body must not leak to later
    // siblings, while outer binds stay visible inside.
    Map<Var, PrimExpr> saved = bind_env_;
    tirx::StmtExprVisitor::VisitStmt_(op);
    bind_env_ = std::move(saved);
  }

private:
  Map<Var, PrimExpr> bind_env_;
};

// 2D layout candidate. Both
// dimensions are tried with their canonical mapping — selected coordinate
// `q * L + lane`, the other coordinate left as-is — over the bound
// lane/chunk/kept ranges. Alias resolution, the loaded-value identity
// rule, the address-node whitelist and the resource limits are the shared
// read-only helpers in pto_index_analysis.h — the same implementation
// AnalyzeBufferAccess uses, so planning and consumption cannot diverge.
// An access passes when its flattened offset is continuous
// (`offset == start + lane`); a load may instead be lane-uniform
// (`offset == start`), while a store must be continuous (lane-uniform
// stores are rejected downstream). A candidate is valid once every
// access proof passes over the padded chunk domain (`q in [0, Q)`,
// `lane in [0, L)`); when both candidates are valid, the selection rules
// below (non-degenerate-dimension preference, then the inner preference)
// apply.
// Layout-inference code reports construct-time failures as
// LoopLayoutInjectiveException (the type LayoutInference catches to discard
// an attempt), while the shared padding helper speaks PtoAnalysisError;
// translate here so all three call sites share one helper.
std::pair<int64_t, int64_t> CheckedPaddingForInference(int64_t extent,
                                                       int64_t lanes) {
  try {
    return pto::CheckedPtoPadding(extent, lanes);
  } catch (const pto::PtoAnalysisError &err) {
    throw LoopLayoutInjectiveException(err.what());
  }
}

int PtoRequiredVectorDim(const For &root, const Var &iv, const Var &jv,
                         int64_t M, int64_t N, int64_t lanes,
                         std::string *why) {
  PtoAccessCollector collector;
  collector(root->body);

  auto candidate_ok = [&](bool select_inner) -> bool {
    const int64_t sel_extent = select_inner ? N : M;
    const Var &sel_var = select_inner ? jv : iv;
    const Var &kept_var = select_inner ? iv : jv;
    const int64_t kept_extent = select_inner ? M : N;
    // A non-divisible extent is padded to P = ceil(E/L)*L when the
    // fragment is built; the candidate proof below works over the padded
    // domain (Q = P/L chunks), which includes the tail chunk's full lane
    // range, and the analyzer proves continuity over that whole padded
    // domain. What remains a caller guarantee is only the *readability*
    // of the padded range past E on the selected axis (tail loads read
    // it); the candidate neither proves nor rejects that.
    // Shared checked padding (rejects extents above the int32 index space
    // before the addition; the same helper the fragment construction uses).
    const auto [pad, padded_extent] =
        CheckedPaddingForInference(sel_extent, lanes);
    (void)pad;
    const int64_t chunk_count = padded_extent / lanes;
    DataType dt = sel_var.dtype();
    Var lane("probe_lane", dt);
    Var q("probe_q", dt);
    PrimExpr sel_expr = q * IntImm(dt, lanes) + lane;
    for (const auto &access : collector.accesses) {
      // Resolve Bind aliases per index with the shared resolver (cycle /
      // depth / loaded-value failure, 4096-node budget, error conversion)
      // against this access's program-point environment, then apply the
      // shared address-node whitelist — the same order AnalyzeBufferAccess
      // uses.
      Array<PrimExpr> resolved;
      for (const auto &idx : access.indices) {
        Optional<PrimExpr> opt;
        try {
          opt = pto::ResolveIndexAliases(idx, access.bind_env);
        } catch (const pto::PtoAnalysisError &err) {
          *why = err.what();
          return false;
        }
        if (!opt.has_value()) {
          std::ostringstream oss;
          oss << "buffer `" << access.buffer->name
              << "`: bind alias chain in index is too deep, cyclic, or "
                 "depends on a loaded value (data-dependent addresses are "
                 "not supported in the first version)";
          *why = oss.str();
          return false;
        }
        resolved.push_back(opt.value());
      }
      for (const auto &idx : resolved) {
        if (!pto::IsSupportedAddressExpr(idx)) {
          std::ostringstream oss;
          oss << "buffer `" << access.buffer->name
              << "`: address expression contains an unsupported call "
                 "(opaque/extern calls cannot appear in addresses; they "
                 "would be evaluated once per chunk instead of per element)";
          *why = oss.str();
          return false;
        }
      }
      // indices under the candidate mapping, then the flattened element
      // offset (same construction as the consumers).
      Array<PrimExpr> indices_after;
      for (const auto &idx : resolved) {
        indices_after.push_back(
            pto::SubstituteVar(idx, sel_var.get(), sel_expr));
      }
      Array<PrimExpr> raw = access.buffer->ElemOffset(indices_after);
      if (raw.size() != 1) {
        *why = "multi-axis element offsets are not supported";
        return false;
      }
      PrimExpr off = raw[0];
      Array<PrimExpr> start_indices;
      for (const auto &idx : indices_after) {
        start_indices.push_back(
            pto::SubstituteVar(idx, lane.get(), make_zero(dt)));
      }
      PrimExpr start = access.buffer->ElemOffset(start_indices)[0];
      arith::Analyzer probe;
      probe.Bind(lane, Range::FromMinExtent(make_zero(dt), IntImm(dt, lanes)));
      // In-row chunk range only: q is the per-row chunk index in [0, Q),
      // never the global position (K*Q for a kept extent K). The kept
      // coordinate is separately bounded below, so the proof domain is
      // exactly (q, lane, kept) — the same domain the final consumers'
      // proof uses.
      probe.Bind(q,
                 Range::FromMinExtent(make_zero(dt), IntImm(dt, chunk_count)));
      // The kept coordinate is bounded by its loop extent; the
      // final consumers' proof binds the same fact.
      probe.Bind(kept_var,
                 Range::FromMinExtent(make_zero(dt), IntImm(dt, kept_extent)));
      const bool continuous = probe.CanProveEqual(off, start + lane);
      const bool uniform = probe.CanProveEqual(
          off,
          probe.Simplify(pto::SubstituteVar(off, lane.get(), make_zero(dt))));
      if (!continuous && !(uniform && !access.is_write)) {
        std::ostringstream oss;
        oss << "buffer `" << access.buffer->name << "` ("
            << (access.is_write ? "store" : "load")
            << ") is neither continuous nor lane-uniform under the "
            << (select_inner ? "inner (j)" : "outer (i)") << " mapping";
        *why = oss.str();
        return false;
      }
    }
    return true;
  };

  std::string inner_why;
  std::string outer_why;
  const bool inner_ok = candidate_ok(/*select_inner=*/true);
  if (!inner_ok) {
    inner_why = *why;
  }
  const bool outer_ok = candidate_ok(/*select_inner=*/false);
  if (!outer_ok) {
    outer_why = *why;
  }
  if (inner_ok && outer_ok && N == 1 && M > 1) {
    // Both dims classify and only the outer is non-degenerate (design
    // 4.6.1): selecting the inner (extent-1) dim would emit M chunks with
    // one valid lane each, while the outer dim covers the same logical
    // points in ceil(M/L) chunks carrying M valid lanes in total. The
    // candidate proofs above have already checked the actual buffer
    // indices and strides, so the preference only breaks the tie between
    // two already-legal candidates and never overrides an access
    // constraint. The symmetric M == 1 && N > 1 falls through to the
    // inner preference below.
    return 0;
  }
  if (inner_ok) {
    // Inner preference; a degenerate dimension is
    // only an interpretation when its accesses classify under the padded
    // domain, which candidate_ok already enforces.
    return 1;
  }
  if (outer_ok) {
    return 0;
  }
  std::ostringstream oss;
  oss << "no vectorizable dimension: inner (j) -> " << inner_why
      << "; outer (i) -> " << outer_why;
  *why = oss.str();
  return -1;
}

} // namespace

// PTO SIMD lane layout: logical points of the parallel loop are distributed
// over [0, L) lanes. The flattened logical index is
//   1D:      t = i
//   2D:      t = i * N + j (j vectorized) or t = j * M + i (i vectorized)
// with lane = t % L and per-lane chunk position p = t // L; forward_index
// holds p. vectorize_size is fixed at 1 — the per-thread SIMT vector-width
// selection does not apply.
//
// Scope note: this function only *builds* the lane fragment. The full input
// contract (access patterns, dtype, expression whitelist) belongs to
// VerifyParallelToPTO; the checks below are only the minimal conditions
// needed to construct a valid layout, reported as layout-inference errors.
LayoutMap
ParallelOpNode::InferPtoSimdLayout(const LayoutInferArgs &layout_args) const {
  const int64_t *lanes_ptr = as_const_int(layout_args.thread_bounds->extent);
  ICHECK(lanes_ptr != nullptr && *lanes_ptr > 0)
      << "[PTO layout inference] lane count must be a positive compile-time "
         "constant, got "
      << layout_args.thread_bounds->extent;
  int64_t lanes = *lanes_ptr;

  // Loop extents must be compile-time constants (first version). Keep the
  // int64 value: narrowing here would silently truncate large static
  // extents.
  std::vector<int64_t> extents;
  for (const auto &iv : loop_vars_) {
    const int64_t *ext = as_const_int(iv->dom->extent);
    ICHECK(ext != nullptr)
        << "[PTO layout inference] requires compile-time constant loop "
           "extents, got "
        << iv->dom->extent << " for loop " << iv->var->name_hint;
    ICHECK(is_zero(iv->dom->min))
        << "[PTO layout inference] requires loop min = 0, got " << iv->dom->min
        << " for loop " << iv->var->name_hint;
    extents.push_back(*ext);
  }
  ICHECK(loop_vars_.size() == 1u || loop_vars_.size() == 2u)
      << "[PTO layout inference] supports a 1D T.Parallel or a two-layer "
         "Parallel nest; got "
      << loop_vars_.size() << " layers";

  // 1D mapping: t = i, lane = i % L,
  // forward_index = [i // L]. A non-divisible extent E is padded to
  // P = ceil(E/L)*L in the *fragment input space only* — the IterVar extent
  // below is the padded one, while buffer addresses keep using the real
  // extents/strides (the tail's readable range is a caller precondition).
  DataType idx_dtype = loop_vars_[0]->var.dtype();
  PrimExpr flattened;
  // The forward vars handed to the Fragment constructor: the selected
  // dimension's IterVar is padded up to P so the thread extent L times the
  // chunk extent P/L covers the padded input space bijectively; the kept
  // dimension keeps its original extent.
  Array<IterVar> frag_vars;
  if (loop_vars_.size() == 1u) {
    const int64_t E = extents[0];
    const auto [pad, P] = CheckedPaddingForInference(E, lanes);
    frag_vars = loop_vars_;
    if (pad != 0) {
      // Reuse the loop var; only the input-space extent is padded.
      frag_vars.Set(0, IterVar(Range::FromMinExtent(make_zero(idx_dtype),
                                                    IntImm(idx_dtype, P)),
                               loop_vars_[0]->var, IterVarType::kDataPar));
    }
    flattened = InputPlaceholder(0);
  } else {
    // 2D mapping: the vectorized dimension is
    // chosen from the buffer accesses (indices + strides), then the
    // logical space is flattened as t = i * P_N + j (j vectorized) or
    // t = j * P_M + i (i vectorized), where P_* is the *padded* selected
    // extent — the flattened global position p lives in [0, K*Q*L) over the
    // padded input space. Both extents stay compile-time constants.
    const int64_t M = extents[0];
    const int64_t N = extents[1];
    const Var &i_var = loop_vars_[0]->var;
    const Var &j_var = loop_vars_[1]->var;
    std::string candidate_why;
    int required =
        PtoRequiredVectorDim(root_, i_var, j_var, M, N, lanes, &candidate_why);
    if (required < 0) {
      // Both candidates failed (an access that is neither continuous nor a
      // lane-uniform load under the padded domain). Report the concrete
      // access and reason — the candidate check already applies the
      // inner-dimension preference, so -1 never means "no constraint".
      std::ostringstream oss;
      oss << "[PTO layout inference] the 2D unit has no vectorizable "
             "dimension (M="
          << M << ", N=" << N << ", L=" << lanes << "): " << candidate_why;
      throw LoopLayoutInjectiveException(oss.str());
    }
    const bool select_inner = required == 1;
    const int64_t sel_extent = select_inner ? N : M;
    const int64_t kept_extent = select_inner ? M : N;
    // Shared checked padding for the selected dimension.
    const auto [pad, P_sel] = CheckedPaddingForInference(sel_extent, lanes);
    // The flattened product K*P_sel indexes the int32 loop-var space; both
    // operands of every t = kept * P_sel + sel evaluation must stay
    // representable.
    if (P_sel > std::numeric_limits<int32_t>::max() ||
        kept_extent > std::numeric_limits<int32_t>::max() / P_sel) {
      std::ostringstream oss;
      oss << "[PTO layout inference] padded flattened extent " << kept_extent
          << "*" << P_sel
          << " overflows the int32 index "
             "space for lanes "
          << lanes;
      throw LoopLayoutInjectiveException(oss.str());
    }
    frag_vars = loop_vars_;
    if (pad != 0) {
      frag_vars.Set(select_inner ? 1 : 0,
                    IterVar(Range::FromMinExtent(make_zero(idx_dtype),
                                                 IntImm(idx_dtype, P_sel)),
                            select_inner ? j_var : i_var,
                            IterVarType::kDataPar));
    }
    flattened = select_inner ? InputPlaceholder(0) * IntImm(idx_dtype, P_sel) +
                                   InputPlaceholder(1)
                             : InputPlaceholder(1) * IntImm(idx_dtype, P_sel) +
                                   InputPlaceholder(0);
  }
  PrimExpr lane = FloorMod(flattened, IntImm(idx_dtype, lanes));
  PrimExpr chunk = FloorDiv(flattened, IntImm(idx_dtype, lanes));
  Var rep_var;
  IterVar rep_iter =
      IterVar(Range::FromMinExtent(make_zero(idx_dtype), IntImm(idx_dtype, 1)),
              rep_var, IterVarType::kDataPar);
  auto fragment = Fragment(frag_vars, {chunk}, lane, rep_iter)
                      ->BindThreadRange(layout_args.thread_bounds);

  // The fragment must not only be forward-injective: Vectorize consumes it
  // through Fragment::InverseWithLevel, so a layout that cannot be inverted
  // with the expected level has to fail here, closest to its construction,
  // not deep inside the vectorize pass.
  try {
    auto inverse_info = fragment->InverseWithLevel(
        /*require_padding_guard=*/false);
    ICHECK(inverse_info.second == arith::IterMapLevel::Bijective)
        << "[PTO layout inference] PTO lane layout must invert at "
           "Bijective level, got "
        << static_cast<int>(inverse_info.second) << " for "
        << fragment->DebugOutput();
  } catch (const Error &err) {
    std::ostringstream oss;
    oss << "[PTO layout inference] lane layout cannot be inverted by "
           "InverseWithLevel: "
        << fragment->DebugOutput() << "\n  error: " << err.what()
        << "\n  loop AST: " << root_;
    throw LoopLayoutInjectiveException(oss.str());
  }

  loop_layout_ = fragment;
  loop_layout_inferred_ = true;
  // No buffer layout updates: first-version PTO SIMD loops access
  // shared/global buffers only, which have no per-lane fragment layouts.
  return {};
}

Fragment
ParallelOpNode::ComputePlanCandidate(const LayoutInferArgs &layout_args) const {
  // Vectorize Size must be aware of the buffer_remap
  // As the pass will do post processing to the layout
  auto maybe_remapped_root_ = IfBufferRemapLoopGenerator::run(
      root_, layout_args.buffer_remap, layout_args.layout_map);
  int vector_size = GetVectorizeSize(maybe_remapped_root_, layout_args.analyzer,
                                     layout_args.layout_map);
  if (layout_args.candidate_vector_size_limit > 0) {
    vector_size =
        std::min(vector_size, layout_args.candidate_vector_size_limit);
  }
  DLOG(INFO) << "[PlanLoopPartition] vector_size = " << vector_size << '\n';

  PrimExpr loop_total_size = 1;
  for (Stmt l = root_; l.as<For>().has_value(); l = l.as<For>().value()->body)
    loop_total_size = loop_total_size * l.as<For>().value()->extent;
  DLOG(INFO) << "[PlanLoopPartition] loop_total_size = " << loop_total_size
             << '\n';
  bool has_fragment_access = !indice_map_.empty();
  if (has_fragment_access) {
    while (!analyzer_.CanProve(
               floormod(loop_total_size, layout_args.thread_bounds->extent *
                                             vector_size) == 0) &&
           vector_size > 1) {
      vector_size /= 2;
    }
  } else if (!root_->annotations.count(attr::kCoalescedWidth)) {
    vector_size = SelectMinPaddingVectorSize(vector_size, loop_total_size,
                                             layout_args.thread_bounds->extent,
                                             &analyzer_);
  }
  DLOG(INFO) << "[PlanLoopPartition] after adjust: vector_size = "
             << vector_size << '\n';

  // Check if coalesced_width is defined
  if (auto coalesced_width = root_->annotations.Get(attr::kCoalescedWidth)) {
    if (const auto *imm = coalesced_width->as<IntImmNode>()) {
      int expected = imm->value;
      // Verify that vector_size is divisible by expected
      if (vector_size % expected != 0) {
        LOG(FATAL) << "Vector size " << vector_size
                   << " is not divisible by coalesced width " << expected;
      }
      vector_size = expected;
    } else {
      LOG(FATAL) << "coalesced_width should be an IntImmNode.";
    }
  }
  DLOG(INFO) << "[PlanLoopPartition] root_ = " << root_
             << " ############# vector_size = " << vector_size
             << ", thread_bounds = " << layout_args.thread_bounds << '\n';
  auto plan = PlanLoopPartition(root_, vector_size, layout_args.thread_bounds);
  DLOG(INFO) << "[PlanLoopPartition] candidate = " << plan->DebugOutput()
             << '\n';
  return plan;
}

void ParallelOpNode::BuildReplicationGuardsIfNeeded(
    const LayoutInferArgs &layout_args,
    const std::vector<Buffer> &store_shared_global_buffers,
    const std::vector<Buffer> &store_fragment_buffers,
    bool has_cross_thread_access,
    const std::vector<Buffer> &const_index_fragment_buffer) const {
  if (is_one(loop_layout_->ReplicateExtent()))
    return;
  if (!has_cross_thread_access)
    return;

  if (!store_fragment_buffers.empty()) {
    bool replicate_is_from_dynamic_index_fragment = false;
    for (const auto &fragment : store_fragment_buffers) {
      if (!layout_args.layout_map.count(fragment)) {
        continue;
      }

      auto fragment_layout =
          layout_args.layout_map[fragment].as<Fragment>().value();
      if (is_one(fragment_layout->ReplicateExtent()))
        continue;

      if (analyzer_.CanProveEqual(fragment_layout->ReplicateExtent(),
                                  loop_layout_->ReplicateExtent()))
        continue;
      if (std::find(const_index_fragment_buffer.begin(),
                    const_index_fragment_buffer.end(),
                    fragment) == const_index_fragment_buffer.end()) {
        replicate_is_from_dynamic_index_fragment = true;
      }
    }

    if (!replicate_is_from_dynamic_index_fragment)
      return;

    ICHECK(store_shared_global_buffers.empty())
        << "Invalid layout: cannot have both fragment and shared store buffers "
           "in replicated loop layout.";
    return;
  } else {
    auto inv = loop_layout_->Inverse();
    Array<PrimExpr> fwd;
    for (size_t i = 0; i < loop_layout_->OutputDim(); i++)
      fwd.push_back(0);
    fwd.push_back(InputPlaceholder(0) - layout_args.thread_bounds->min);
    auto rep = inv->Forward(fwd).back();
    AddPredicate(EQ(rep, 0));
  }
}
Fragment
ParallelOpNode::ChooseBestCandidate(const Fragment &candidate_from_buffer,
                                    const Fragment &candidate_from_plan,
                                    const LayoutInferArgs &layout_args) const {
  // Strategy overview:
  // 1) Validate each candidate against all known source fragments. If only one
  //    is compatible, choose it immediately.
  // 2) If both are compatible, compare their containment relation:
  //      - If buffer-based contains plan-based, prefer plan (usually smaller
  //      rep).
  //      - If plan-based contains buffer-based, prefer buffer.
  // 3) If neither contains the other, prefer the one with provably smaller or
  //    equal replication extent; otherwise fall back to buffer-based candidate.
  // Note: Final global validation happens after selection elsewhere.
  auto vars =
      loop_vars_.Map([](const IterVar &iv) { return PrimExpr(iv->var); });
  auto contains = [&](const Fragment &big, const Fragment &small) {
    // contains(A, B) means: for any loop index, the threads that access
    // B's elements are a subset of those that access A's elements.
    return ProveFragmentContains(small, big, vars, vars, analyzer_);
  };

  bool buf_ok =
      ValidateCandidateAgainstFragments(candidate_from_buffer, layout_args);
  bool plan_ok =
      ValidateCandidateAgainstFragments(candidate_from_plan, layout_args);

  if (buf_ok && !plan_ok) {
    DLOG(INFO)
        << "[FreeInfer] prefer compute_from_buffer (only valid candidate).";
    return candidate_from_buffer;
  }
  if (plan_ok && !buf_ok) {
    DLOG(INFO)
        << "[FreeInfer] prefer PlanLoopPartition (only valid candidate).";
    return candidate_from_plan;
  }
  if (!(buf_ok && plan_ok)) {
    // Both invalid here; let the caller continue to final validation/throw.
    // Returning buffer-based candidate keeps behavior deterministic.
    return candidate_from_buffer; // arbitrary; caller will catch later
  }

  // Both candidates may be semantically valid for reads from a fully
  // replicated fragment.  The plan candidate often minimizes replication by
  // assigning one logical element to each CUDA thread, but that can turn a
  // register fragment access into `fragment[threadIdx.x]`.  CUDA cannot keep a
  // register array with runtime indexing in scalar registers, so this shape
  // spills the whole fragment to local memory — a catastrophe regardless of
  // where the loop's stores go (a fragment->fragment publication copy spills
  // exactly the same way as a fragment->global one), so the preference is
  // unconditional: when exactly one valid candidate keeps every fragment
  // physical index independent of the thread variable, choose it.  For a
  // fully replicated readback this selects the fragment-derived layout;
  // BuildReplicationGuardsIfNeeded then emits the single-replica guard for
  // shared/global stores, and fragment stores legitimately execute on every
  // replica.
  {
    bool buf_thread_index =
        HasThreadDependentFragmentIndex(candidate_from_buffer, layout_args);
    bool plan_thread_index =
        HasThreadDependentFragmentIndex(candidate_from_plan, layout_args);
    if (buf_thread_index != plan_thread_index) {
      return buf_thread_index ? candidate_from_plan : candidate_from_buffer;
    }
  }

  bool buf_contains_plan = contains(candidate_from_buffer, candidate_from_plan);
  bool plan_contains_buf = contains(candidate_from_plan, candidate_from_buffer);

  auto rep_buf = candidate_from_buffer->ReplicateExtent();
  auto rep_plan = candidate_from_plan->ReplicateExtent();

  // Prefer the contained candidate (tends to minimize replication while
  // respecting access coverage):
  if (buf_contains_plan && !plan_contains_buf) {
    return candidate_from_plan;
  }
  if (plan_contains_buf && !buf_contains_plan) {
    return candidate_from_buffer;
  }
  // Neither strictly contains the other; prefer the one with smaller/equal rep.
  if (analyzer_.CanProve(rep_plan <= rep_buf)) {
    return candidate_from_plan;
  }
  // Safe fallback: buffer-based candidate is always correct.
  return candidate_from_buffer;
}

FragmentThreadIndexProbe::FragmentThreadIndexProbe(
    const Fragment &loop_layout, const Array<IterVar> &loop_vars,
    arith::Analyzer *analyzer)
    : thread_var_("__tl_candidate_thread"), analyzer_(analyzer) {
  // Mirror the index substitution that PartitionLoop would apply for this
  // loop layout without actually rebuilding the loop: symbolic per-thread
  // output coordinates plus a symbolic thread variable, inverted back to
  // the original loop variables.
  if (!loop_layout.defined() || loop_layout->InputDim() != loop_vars.size()) {
    return;
  }
  Array<PrimExpr> partition_vars;
  for (size_t i = 0; i < loop_layout->OutputDim(); ++i) {
    Var coord("__tl_candidate_i" + std::to_string(i));
    // Bind every symbolic coordinate's range: the thread-cancellation proofs
    // below are range-dependent (e.g. `(o0*512 + t*4 + o1) // 512 -> o0`
    // only holds for t*4 + o1 < 512), and an unbound var makes Simplify
    // keep the thread term, flagging clean strided layouts as spilling.
    analyzer->Bind(coord, Range::FromMinExtent(make_zero(DataType::Int(32)),
                                               loop_layout->OutputShape()[i]));
    partition_vars.push_back(coord);
  }
  partition_vars.push_back(thread_var_);
  if (loop_layout->ThreadRange().defined()) {
    analyzer->Bind(thread_var_,
                   Range::FromMinExtent(loop_layout->ThreadRange()->min,
                                        loop_layout->ThreadRange()->extent));
  } else {
    analyzer->Bind(thread_var_,
                   Range::FromMinExtent(make_zero(DataType::Int(32)),
                                        loop_layout->ThreadExtent()));
  }

  Array<PrimExpr> recovered_indices;
  try {
    auto inv_loop = loop_layout->InverseWithLevel().first;
    recovered_indices = inv_loop->Forward(partition_vars);
  } catch (const std::exception &) {
    // Non-invertible layout: leave the probe invalid — callers must treat
    // this as "unknown", never as "clean".
    return;
  }

  for (size_t i = 0; i < loop_vars.size(); ++i) {
    loop_var_map_.Set(loop_vars[i]->var, recovered_indices[i]);
  }
  if (loop_layout->ThreadRange().defined()) {
    auto range = loop_layout->ThreadRange();
    thread_offset_map_.Set(thread_var_, thread_var_ - range->min);
    has_thread_offset_ = true;
  }
  valid_ = true;
}

bool FragmentThreadIndexProbe::AccessUsesThread(
    const Array<PrimExpr> &access_indices,
    const Fragment &fragment_layout) const {
  if (!valid_ || !fragment_layout.defined()) {
    return false;
  }
  Array<PrimExpr> indices = access_indices.Map(
      [&](const PrimExpr &index) { return Substitute(index, loop_var_map_); });
  if (has_thread_offset_) {
    indices = Substitute(indices, thread_offset_map_);
  }
  Array<PrimExpr> physical_indices = fragment_layout->Forward(indices);
  for (const auto &index : physical_indices) {
    PrimExpr simplified = analyzer_->Simplify(index);
    if (tirx::UsesVar(simplified, [&](const VarNode *var_node) {
          return GetRef<Var>(var_node).same_as(thread_var_);
        })) {
      return true;
    }
  }
  return false;
}

bool ParallelOpNode::HasThreadDependentFragmentIndex(
    const Fragment &candidate, const LayoutInferArgs &layout_args) const {
  // If any physical fragment index still contains the symbolic thread
  // variable, lowering this candidate would emit a runtime-thread-indexed
  // register array access such as `fragment[threadIdx.x]`.
  FragmentThreadIndexProbe probe(candidate, loop_vars_, &analyzer_);
  if (!probe.valid()) {
    return false;
  }
  for (const auto &buffer : access_order_) {
    if (!IsFragmentBuffer(buffer) || !layout_args.layout_map.count(buffer)) {
      continue;
    }
    auto fragment_layout = layout_args.layout_map[buffer].as<Fragment>();
    if (!fragment_layout.has_value()) {
      continue;
    }
    if (probe.AccessUsesThread(GetAccessInfo(buffer).indices,
                               fragment_layout.value())) {
      return true;
    }
  }
  return false;
}

} // namespace tl
} // namespace tvm
